const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser = await chromium.launch({headless:true, executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});
 const page=await browser.newPage({viewport:{width:1741,height:1100}});
 page.on('pageerror',e=>console.log('PAGE ERROR',e.message));
 await page.goto('http://localhost:3000');
 await page.evaluate(()=>sessionStorage.setItem('p7-current-page','persona'));
 await page.reload();
 await page.getByRole('button',{name:'设计规范',exact:true}).click();
 await page.waitForTimeout(1000);
 console.log('BOUNDS',await page.locator('.deck-canvas').boundingBox(),await page.locator('#design-panel').boundingBox());
 await page.locator('[data-design-card]').first().click({position:{x:10,y:10}});
 console.log('SELECTED',await page.locator('[data-element-selected]').getAttribute('data-design-card'));
 await page.getByLabel('宽度模式',{exact:true}).selectOption('fixed');
 const before=await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).width);
 await page.getByLabel('自定义宽度（px）',{exact:true}).fill('350');
 await page.waitForTimeout(100);
 console.log('PREVIEW',before,await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).width));
 await page.getByRole('button',{name:'取消预览',exact:true}).click();
 console.log('CANCEL',await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).width));
 await page.getByLabel('自定义宽度（px）',{exact:true}).fill('350');
 await page.getByRole('button',{name:'存为规范并应用',exact:true}).click();
 console.log('COMMIT',await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).width));
 await page.getByRole('button',{name:'撤销',exact:true}).click();
 console.log('UNDO',await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).width));
 await page.getByRole('button',{name:'重做',exact:true}).click();
 console.log('REDO',await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).width));
 await page.reload();
 await page.getByRole('button',{name:'设计规范',exact:true}).click();
 console.log('RELOAD',await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).width));
 await page.locator('[data-design-card] h3').first().click();
 await page.getByLabel('文字内容',{exact:true}).fill('王总测试');
 await page.getByRole('button',{name:'应用文字',exact:true}).click();
 console.log('TEXT',await page.locator('[data-design-card] h3').first().textContent());
 await page.getByRole('button',{name:'撤销',exact:true}).click();
 console.log('TEXT UNDO',await page.locator('[data-design-card] h3').first().textContent());
 await page.getByRole('button',{name:'重做',exact:true}).click();
 console.log('TEXT REDO',await page.locator('[data-design-card] h3').first().textContent());
 await page.locator('[data-design-card]').first().click({position:{x:10,y:10}});
 await page.getByLabel('内边距',{exact:true}).selectOption('space-16');
 await page.waitForTimeout(400);
 console.log('PADDING',await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).padding));
 await page.getByRole('button',{name:'撤销',exact:true}).click();
 await page.waitForTimeout(400);
 console.log('PADDING UNDO',await page.locator('[data-design-card]').first().evaluate(e=>getComputedStyle(e).padding));
 await page.screenshot({path:'/tmp/p7-editor-check/editor.png'});
 await browser.close();
})();
