export type Rule = { id: string; name: string; purpose: string; kind: string; values: Record<string, string> };
export const libraryDefaults: Rule[] = [
  { id: 'research-data', name: '研究数据', purpose: '问卷结果百分比', kind: 'type', values: { 'font-size': '32px', 'font-weight': '700', 'line-height': '1.1', color: 'var(--color-primary)' } },
  { id: 'size-remaining', name: '分配剩余空间', purpose: '沿父布局伸展', kind: 'size', values: { value: 'auto', mode: 'remaining' } },
  ...[1, 2, 3, 4].map(n => ({ id: `columns-${n}`, name: `${n} 列等宽`, purpose: '网格列数', kind: 'columns', values: { value: `repeat(${n}, minmax(0, 1fr))` } })),
  ...[['start', '起点对齐'], ['center', '居中对齐'], ['end', '终点对齐'], ['stretch', '拉伸对齐']].map(([value, name]) => ({ id: `align-${value}`, name, purpose: '子元素对齐', kind: 'alignment', values: { value } })),
  ...[['start', '起点排列'], ['center', '居中排列'], ['end', '终点排列'], ['space-between', '两端排列'], ['space-evenly', '均匀排列']].map(([value, name]) => ({ id: `distribute-${value}`, name, purpose: '内容分布', kind: 'distribution', values: { value } })),
  ...[['row', '横向'], ['column', '纵向']].map(([value, name]) => ({ id: `direction-${value}`, name, purpose: '弹性布局方向', kind: 'direction', values: { value } })),
  ...[['display', '大标题', '48px', '700', '1.2'], ['title', '页内标题', 'var(--ds-title)', '700', '1.35'], ['card', '卡片标题', '14px', '700', '1.4'], ['body', '正文说明', 'var(--ds-explanation)', 'var(--ds-explanation-weight)', '1.6'], ['caption', '辅助标注', '11px', '500', '1.5']].map(([id, name, size, weight, height]) => ({ id, name, purpose: name, kind: 'type', values: { 'font-size': size, 'font-weight': weight, 'line-height': height, color: id === 'body' ? 'var(--ds-explanation-color)' : id === 'caption' ? '#64748b' : 'var(--color-heading)' } })),
  ...[['brand', '品牌色', 'var(--color-primary)'], ['ink', '标题色', 'var(--color-heading)'], ['body-color', '正文色', '#475569'], ['muted', '辅助文字色', '#64748b'], ['canvas', '画布色', 'var(--slide-bg)'], ['white', '白色', '#ffffff'], ['border', '边框色', '#cbd5e1'], ['transparent', '透明', 'transparent']].map(([id, name, value]) => ({ id, name, purpose: name, kind: 'color', values: { value } })),
  ...[['sm', 'S'], ['md', 'M'], ['lg', 'L'], ['xl', 'XL'], ['full', '胶囊']].map(([id, name]) => ({ id: `radius-${id}`, name, purpose: '圆角', kind: 'radius', values: { value: id === 'full' ? '999px' : `var(--radius-${id})` } })),
  ...[['auto', '自动尺寸', 'auto'], ['content', '适应内容', 'fit-content'], ['full', '填满父容器', '100%']].map(([id, name, value]) => ({ id: `size-${id}`, name, purpose: '宽度与高度', kind: 'size', values: { value } })),
  ...[48, 64, 96, 128, 160, 192, 240, 320, 400, 480, 560, 640].map(n => ({ id: `size-${n}`, name: `尺寸 ${n}`, purpose: '固定宽度与高度', kind: 'size', values: { value: `${n}px` } })),
  ...[0, 4, 5, 8, 12, 16, 24, 32, 40, 48].map(n => ({ id: `space-${n}`, name: `${n}px`, purpose: '内边距、外边距与布局间距', kind: 'space', values: { value: `${n}px` } })),
];
export const slots = [['grid-template-columns', '网格列数', 'columns'], ['flex-direction', '排列方向', 'direction'], ['align-items', '子元素对齐', 'alignment'], ['justify-content', '内容分布', 'distribution'], ['typography', '文字样式', 'type'], ['color', '文字颜色', 'color'], ['width', '宽度', 'size'], ['height', '高度', 'size'], ['background-color', '背景颜色', 'color'], ['border-color', '边框颜色', 'color'], ['border-radius', '圆角', 'radius'], ['padding-top', '上内边距', 'space'], ['padding-bottom', '下内边距', 'space'], ['padding-left', '左内边距', 'space'], ['padding-right', '右内边距', 'space'], ['margin-top', '上外边距', 'space'], ['margin-bottom', '下外边距', 'space'], ['margin-left', '左外边距', 'space'], ['margin-right', '右外边距', 'space'], ['row-gap', '行间距', 'space'], ['column-gap', '列间距', 'space']];
